import { cp, mkdir, mkdtemp, readFile, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { describe, expect, it } from "vitest";
import { main } from "../src/cli/main.js";

const FIXTURES_ROOT = join(import.meta.dirname, "fixtures");

interface CapturedRun {
  readonly code: number;
  readonly stdout: string;
  readonly stderr: string;
}

describe("apolo cli", () => {
  it("shows the visible command surface", async () => {
    const run = await runCli(["--help"]);

    expect(run.code).toBe(0);
    expect(run.stdout).toContain("apolo init");
    expect(run.stdout).toContain("apolo doctor");
    expect(run.stdout).toContain("apolo agents");
  });

  it("initializes generic APOLO harness artifacts", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "apolo-repo-"));
    const home = await mkdtemp(join(tmpdir(), "apolo-home-"));
    const run = await runCli(["init"], cwd, home);

    expect(run.code).toBe(0);
    const manifest = await readFile(join(cwd, ".apolo", "manifest.json"), "utf8");
    expect(manifest).toContain('"provider": "claude"');
    expect(manifest).toContain('"defaultModel": "qwen"');
    expect(manifest).toContain('"maxPerTask": 5');
    expect(manifest).toContain('"initMode": "pull-request"');
    expect(manifest).toContain('"directMain": false');
    expect(manifest).toContain('"backends": [\n      "typescript"\n    ]');

    const apoloYaml = await readFile(join(cwd, ".apolo", "apolo.yaml"), "utf8");
    expect(apoloYaml).toContain("Generated by APOLO init");
    expect(apoloYaml).toContain("plans: .apolo/plans");
    expect(apoloYaml).toContain("runs: .apolo/runs");
    expect(apoloYaml).toContain("memory: .apolo/memory");
    expect((await stat(join(cwd, ".apolo", "plans"))).isDirectory()).toBe(true);
    expect((await stat(join(cwd, ".apolo", "runs"))).isDirectory()).toBe(true);
    expect((await stat(join(cwd, ".apolo", "memory"))).isDirectory()).toBe(true);
  });

  it("reports dry-run init as JSON without writing files", async () => {
    const cwd = await fixtureWorkspace("node-vite");
    const home = await mkdtemp(join(tmpdir(), "apolo-home-"));
    const run = await runCli(["init", "--dry-run", "--format", "json"], cwd, home);

    expect(run.code).toBe(0);
    const payload = JSON.parse(run.stdout) as {
      mode: string;
      summary: { creates: string[] };
      detectedStack: { commands: { test: string[]; build: string[] } };
    };
    expect(payload.mode).toBe("dry-run");
    expect(payload.summary.creates).toContain(".apolo/apolo.yaml");
    expect(payload.detectedStack.commands.test).toContain("npm run test");
    expect(payload.detectedStack.commands.build).toContain("npm run build");
    await expect(stat(join(cwd, ".apolo"))).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("is idempotent after workspace creation", async () => {
    const cwd = await fixtureWorkspace("node-vite");
    const home = await mkdtemp(join(tmpdir(), "apolo-home-"));
    const first = await runCli(["init"], cwd, home);
    const second = await runCli(["init", "--format=json"], cwd, home);

    expect(first.code).toBe(0);
    expect(second.code).toBe(0);
    const payload = JSON.parse(second.stdout) as {
      summary: { creates: string[]; updates: string[]; skips: string[]; conflicts: string[] };
    };
    expect(payload.summary.creates).toEqual([]);
    expect(payload.summary.updates).toEqual([]);
    expect(payload.summary.conflicts).toEqual([]);
    expect(payload.summary.skips).toContain(".apolo/apolo.yaml");
  });

  it("detects conflicts without overwriting user files", async () => {
    const cwd = await fixtureWorkspace("node-vite");
    const home = await mkdtemp(join(tmpdir(), "apolo-home-"));
    await mkdir(join(cwd, ".apolo"), { recursive: true });
    await writeFile(join(cwd, ".apolo", "apolo.yaml"), "user-owned: true\n", "utf8");
    const run = await runCli(["init", "--format", "json"], cwd, home);

    expect(run.code).toBe(1);
    const payload = JSON.parse(run.stdout) as { mode: string; summary: { conflicts: string[] } };
    expect(payload.mode).toBe("conflict");
    expect(payload.summary.conflicts).toContain(".apolo/apolo.yaml");
    await expect(readFile(join(cwd, ".apolo", "apolo.yaml"), "utf8")).resolves.toBe("user-owned: true\n");
  });

  it("uses APOLO_HOME as the global APOLO directory", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "apolo-repo-"));
    const home = await mkdtemp(join(tmpdir(), "apolo-home-"));
    const apoloHome = await mkdtemp(join(tmpdir(), "apolo-global-"));
    const run = await runCli(["doctor"], cwd, home, { APOLO_HOME: apoloHome });

    expect(run.code).toBe(0);
    expect(run.stdout).toContain(`global memory: ${join(apoloHome, "memory", "global.sqlite")}`);
    expect(run.stdout).not.toContain(join(apoloHome, ".apolo"));
  });

  it("reports doctor defaults before initialization", async () => {
    const cwd = await mkdtemp(join(tmpdir(), "apolo-repo-"));
    const home = await mkdtemp(join(tmpdir(), "apolo-home-"));
    const run = await runCli(["doctor"], cwd, home);

    expect(run.code).toBe(0);
    expect(run.stdout).toContain("coordinator: claude");
    expect(run.stdout).toContain("approval: always");
    expect(run.stdout).toContain("ollama default model: qwen");
    expect(run.stdout).toContain("max agents per task: 5");
  });

  it("requires approval before run in non-interactive mode", async () => {
    const run = await runCli(["run", "example task"]);

    expect(run.code).toBe(2);
    expect(run.stderr).toContain("requires explicit human approval");
  });

  it("accepts explicit approval for run stub", async () => {
    const run = await runCli(["run", "example task", "--approve"]);

    expect(run.code).toBe(0);
    expect(run.stdout).toContain("task execution interface ready");
  });
});

async function runCli(
  args: readonly string[],
  cwd?: string,
  home?: string,
  env: Record<string, string> = {}
): Promise<CapturedRun> {
  let stdout = "";
  let stderr = "";
  const resolvedCwd = cwd ?? (await mkdtemp(join(tmpdir(), "apolo-repo-")));
  const resolvedHome = home ?? (await mkdtemp(join(tmpdir(), "apolo-home-")));
  const code = await main(args, {
    cwd: resolvedCwd,
    env: {
      HOME: resolvedHome,
      ...env
    },
    isInteractive: false,
    stdout: {
      write: (chunk) => {
        stdout += chunk;
      }
    },
    stderr: {
      write: (chunk) => {
        stderr += chunk;
      }
    },
    readLine: async () => ""
  });

  return { code, stdout, stderr };
}

async function fixtureWorkspace(name: string): Promise<string> {
  const cwd = await mkdtemp(join(tmpdir(), "apolo-fixture-"));
  await cp(join(FIXTURES_ROOT, name), cwd, { recursive: true });
  return cwd;
}
