from __future__ import annotations

import json
from datetime import datetime, timezone

from .handoff import HandoffSummary
from .models import GeneratedFile, RepoScan, StackDetection, WritePlan
from .templates import TemplateRenderer

GENERATED_MARKER = "Generated by APOLO init"


def build_harness_plan(scan: RepoScan, detection: StackDetection, handoff: HandoffSummary) -> WritePlan:
    renderer = TemplateRenderer()
    profile = _project_profile(scan, detection)
    manifest = _manifest(scan, detection)
    variables = _template_variables(scan, detection, profile, manifest, handoff)

    files = [
        _template_file("AGENTS.md", "AGENTS.md.tpl", variables),
        _template_file("CLAUDE.md", "CLAUDE.md.tpl", variables),
        _template_file("apolo.yaml", "apolo.yaml.tpl", variables),
        GeneratedFile("feature_list.json", _json(profile["features"])),
        _template_file("apolo-progress.md", "apolo-progress.md.tpl", variables),
        _template_file("session-handoff.md", "session-handoff.md.tpl", variables),
        _template_file("quality-document.md", "quality-document.md.tpl", variables),
        _template_file("init.sh", "init.sh.tpl", variables, executable=True),
        GeneratedFile(".apolo/manifest.json", _json(manifest)),
        GeneratedFile(".apolo/project-profile.json", _json(profile)),
        _template_file(".apolo/gates.yaml", "gates.yaml.tpl", variables),
        GeneratedFile(".apolo/plans/.gitkeep", ""),
        GeneratedFile(".apolo/reports/.gitkeep", ""),
        _template_file("apolo-memory/README.md", "memory-README.md.tpl", variables),
        GeneratedFile("apolo-memory/facts/.gitkeep", ""),
        GeneratedFile("apolo-memory/decisions/.gitkeep", ""),
        GeneratedFile("apolo-memory/handoffs/.gitkeep", ""),
    ]

    if not detection.tests_present:
        files.append(_minimal_test_file(detection, renderer, variables))

    return WritePlan(repo_root=scan.root, files=files, marker=GENERATED_MARKER)


def _template_file(
    path: str,
    template_name: str,
    variables: dict[str, str],
    executable: bool = False,
) -> GeneratedFile:
    return GeneratedFile(
        relative_path=path,
        content=TemplateRenderer().render(template_name, variables),
        executable=executable,
    )


def _project_profile(scan: RepoScan, detection: StackDetection) -> dict[str, object]:
    return {
        "schema_version": 1,
        "repository": scan.root.name,
        "root": str(scan.root),
        "generated_by": "apolo init",
        "languages": detection.languages,
        "frameworks": detection.frameworks,
        "package_managers": detection.package_managers,
        "tests_present": detection.tests_present,
        "ci_providers": detection.ci_providers,
        "commands": {
            "test": detection.test_commands,
            "lint": detection.lint_commands,
            "build": detection.build_commands,
        },
        "features": [
            {
                "id": "repo-harness",
                "name": "Repository harness",
                "status": "initialized",
                "description": "Generic project harness, quality gates, and handoff structure.",
            }
        ],
    }


def _manifest(scan: RepoScan, detection: StackDetection) -> dict[str, object]:
    return {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": "apolo init",
        "repo": scan.root.name,
        "managed_paths": [
            "AGENTS.md",
            "CLAUDE.md",
            "apolo.yaml",
            "feature_list.json",
            "apolo-progress.md",
            "session-handoff.md",
            "quality-document.md",
            "init.sh",
            ".apolo/manifest.json",
            ".apolo/project-profile.json",
            ".apolo/gates.yaml",
            ".apolo/plans/",
            ".apolo/reports/",
            "apolo-memory/",
        ],
        "detected_stack": detection.to_dict(),
        "handoff_hooks": {
            "git_status": "stub",
            "pull_request": "stub",
            "ci_summary": "stub",
        },
    }


def _template_variables(
    scan: RepoScan,
    detection: StackDetection,
    profile: dict[str, object],
    manifest: dict[str, object],
    handoff: HandoffSummary,
) -> dict[str, str]:
    return {
        "marker": GENERATED_MARKER,
        "repo_name": scan.root.name,
        "languages": _csv(detection.languages),
        "frameworks": _csv(detection.frameworks),
        "package_managers": _csv(detection.package_managers),
        "ci_providers": _csv(detection.ci_providers),
        "test_commands_yaml": _yaml_list(detection.test_commands),
        "lint_commands_yaml": _yaml_list(detection.lint_commands),
        "build_commands_yaml": _yaml_list(detection.build_commands),
        "test_commands_md": _md_list(detection.test_commands),
        "lint_commands_md": _md_list(detection.lint_commands),
        "build_commands_md": _md_list(detection.build_commands),
        "profile_json": _json(profile),
        "manifest_json": _json(manifest),
        "handoff_summary_md": handoff.to_markdown(),
    }


def _minimal_test_file(
    detection: StackDetection,
    renderer: TemplateRenderer,
    variables: dict[str, str],
) -> GeneratedFile:
    if detection.minimal_test_kind == "python":
        return GeneratedFile("tests/test_apolo_smoke.py", renderer.render("test-python.tpl", variables))
    if detection.minimal_test_kind == "node":
        return GeneratedFile("tests/apolo-smoke.test.js", renderer.render("test-node.tpl", variables))
    if detection.minimal_test_kind == "rust":
        return GeneratedFile("tests/apolo_smoke.rs", renderer.render("test-rust.tpl", variables))
    if detection.minimal_test_kind == "go":
        return GeneratedFile("apolo_smoke_test.go", renderer.render("test-go.tpl", variables))
    return GeneratedFile("tests/apolo_smoke_test.sh", renderer.render("test-shell.tpl", variables), executable=True)


def _csv(values: list[str]) -> str:
    return ", ".join(values) if values else "unknown"


def _yaml_list(values: list[str]) -> str:
    if not values:
        return "    []"
    return "\n".join(f"    - {json.dumps(value)}" for value in values)


def _md_list(values: list[str]) -> str:
    if not values:
        return "- Not detected"
    return "\n".join(f"- `{value}`" for value in values)


def _json(value: object) -> str:
    return f"{json.dumps(value, indent=2, sort_keys=True)}\n"
