import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import type { Env } from "../fs/layout.js";
import { createDefaultManifest } from "../config/defaults.js";

export const GENERATED_MARKER = "Generated by APOLO init";

type InitFormat = "text" | "json";
type InitMode = "dry-run" | "write" | "conflict";
type FileStatus = "create" | "update" | "skip" | "conflict";
type ArtifactKind = "file" | "directory";

export interface InitOptions {
  readonly dryRun: boolean;
  readonly force: boolean;
  readonly format: InitFormat;
}

export interface InitSummary {
  readonly creates: readonly string[];
  readonly updates: readonly string[];
  readonly skips: readonly string[];
  readonly conflicts: readonly string[];
}

export interface InitResult {
  readonly mode: InitMode;
  readonly repo: string;
  readonly summary: InitSummary;
  readonly artifacts: readonly string[];
  readonly detectedStack: StackDetection;
}

interface Artifact {
  readonly relativePath: string;
  readonly kind: ArtifactKind;
  readonly content?: string;
}

interface PlannedArtifact extends Artifact {
  readonly status: FileStatus;
}

interface RepoScan {
  readonly root: string;
  readonly files: readonly string[];
}

interface StackDetection {
  readonly languages: readonly string[];
  readonly frameworks: readonly string[];
  readonly packageManagers: readonly string[];
  readonly ciProviders: readonly string[];
  readonly testsPresent: boolean;
  readonly commands: {
    readonly lint: readonly string[];
    readonly test: readonly string[];
    readonly build: readonly string[];
  };
}

const IGNORED_DIRS = new Set([
  ".apolo",
  ".git",
  ".hg",
  ".svn",
  ".idea",
  ".vscode",
  ".venv",
  "venv",
  "env",
  "node_modules",
  "dist",
  "build",
  "target",
  "__pycache__",
  ".pytest_cache",
  ".mypy_cache"
]);

export function parseInitOptions(args: readonly string[]): InitOptions {
  let dryRun = false;
  let force = false;
  let format: InitFormat = "text";

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === "--dry-run") {
      dryRun = true;
      continue;
    }

    if (arg === "--force") {
      force = true;
      continue;
    }

    if (arg === "--json") {
      format = "json";
      continue;
    }

    if (arg === "--format") {
      const value = args[index + 1];
      if (value !== "json" && value !== "text") {
        throw new Error("apolo init --format accepts only `json` or `text`.");
      }
      format = value;
      index += 1;
      continue;
    }

    if (arg?.startsWith("--format=")) {
      const value = arg.slice("--format=".length);
      if (value !== "json" && value !== "text") {
        throw new Error("apolo init --format accepts only `json` or `text`.");
      }
      format = value;
      continue;
    }

    throw new Error(`Unknown apolo init option: ${arg ?? ""}`);
  }

  return { dryRun, force, format };
}

export async function runApoloInit(cwd: string, env: Env, options: InitOptions): Promise<InitResult> {
  const repo = resolve(cwd);
  await assertDirectory(repo);
  const scan = await scanRepo(repo);
  const detectedStack = await detectStack(scan);
  const artifacts = buildArtifacts(repo, env, detectedStack);
  const planned = await classifyArtifacts(repo, artifacts, options.force);
  const summary = summarize(planned);

  if (!options.dryRun && summary.conflicts.length === 0) {
    await applyPlan(repo, planned);
  }

  return {
    mode: resolveInitMode(options, summary),
    repo,
    summary,
    artifacts: artifacts.map((artifact) => artifact.relativePath),
    detectedStack
  };
}

function resolveInitMode(options: InitOptions, summary: InitSummary): InitMode {
  if (options.dryRun) {
    return "dry-run";
  }

  return summary.conflicts.length > 0 ? "conflict" : "write";
}

export function formatInitResult(result: InitResult, format: InitFormat): string {
  if (format === "json") {
    return `${JSON.stringify(result, null, 2)}\n`;
  }

  const lines = [`APOLO init ${result.mode} for ${result.repo}`];
  for (const key of ["creates", "updates", "skips", "conflicts"] as const) {
    const values = result.summary[key];
    if (values.length === 0) {
      continue;
    }
    lines.push(`${key}:`);
    for (const value of values) {
      lines.push(`  - ${value}`);
    }
  }

  if (result.summary.conflicts.length > 0) {
    lines.push("");
    lines.push("Resolve conflicts or rerun with --force to update APOLO-managed files.");
  }

  return `${lines.join("\n")}\n`;
}

function buildArtifacts(repo: string, env: Env, detectedStack: StackDetection): readonly Artifact[] {
  const manifest = {
    ...createDefaultManifest(repo, env),
    generatedBy: GENERATED_MARKER
  };

  return [
    { relativePath: ".apolo", kind: "directory" },
    { relativePath: ".apolo/plans", kind: "directory" },
    { relativePath: ".apolo/runs", kind: "directory" },
    { relativePath: ".apolo/memory", kind: "directory" },
    { relativePath: ".apolo/plans/.gitkeep", kind: "file", content: "" },
    { relativePath: ".apolo/runs/.gitkeep", kind: "file", content: "" },
    { relativePath: ".apolo/memory/.gitkeep", kind: "file", content: "" },
    { relativePath: ".apolo/manifest.json", kind: "file", content: `${JSON.stringify(manifest, null, 2)}\n` },
    { relativePath: ".apolo/apolo.yaml", kind: "file", content: renderApoloYaml(repo, detectedStack) },
    { relativePath: ".apolo/gates.yaml", kind: "file", content: renderGatesYaml(detectedStack) },
    { relativePath: ".apolo/apolo-progress.md", kind: "file", content: renderProgressMarkdown(detectedStack) },
    { relativePath: ".apolo/session-handoff.md", kind: "file", content: renderSessionHandoffMarkdown(repo) },
    { relativePath: ".apolo/quality-document.md", kind: "file", content: renderQualityMarkdown(detectedStack) }
  ];
}

async function classifyArtifacts(
  repo: string,
  artifacts: readonly Artifact[],
  force: boolean
): Promise<readonly PlannedArtifact[]> {
  const planned: PlannedArtifact[] = [];

  for (const artifact of artifacts) {
    planned.push({
      ...artifact,
      status: await classifyArtifact(repo, artifact, force)
    });
  }

  return planned;
}

async function classifyArtifact(repo: string, artifact: Artifact, force: boolean): Promise<FileStatus> {
  const target = resolveArtifact(repo, artifact.relativePath);
  const existing = await statOrNull(target);

  if (!existing) {
    return "create";
  }

  if (artifact.kind === "directory") {
    return existing.isDirectory() ? "skip" : "conflict";
  }

  if (!existing.isFile()) {
    return "conflict";
  }

  const content = artifact.content ?? "";
  const current = await readUtf8(target);
  if (current === content) {
    return "skip";
  }

  if (force || current.includes(GENERATED_MARKER)) {
    return "update";
  }

  return "conflict";
}

function summarize(planned: readonly PlannedArtifact[]): InitSummary {
  return {
    creates: collect(planned, "create"),
    updates: collect(planned, "update"),
    skips: collect(planned, "skip"),
    conflicts: collect(planned, "conflict")
  };
}

function collect(planned: readonly PlannedArtifact[], status: FileStatus): readonly string[] {
  return planned.filter((artifact) => artifact.status === status).map((artifact) => formatArtifactPath(artifact));
}

async function applyPlan(repo: string, planned: readonly PlannedArtifact[]): Promise<void> {
  for (const artifact of planned) {
    if (artifact.status !== "create" && artifact.status !== "update") {
      continue;
    }

    const target = resolveArtifact(repo, artifact.relativePath);
    if (artifact.kind === "directory") {
      await mkdir(target, { recursive: true });
      continue;
    }

    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, artifact.content ?? "", "utf8");
  }
}

async function assertDirectory(path: string): Promise<void> {
  const existing = await stat(path);
  if (!existing.isDirectory()) {
    throw new Error(`Repository path is not a directory: ${path}`);
  }
}

async function scanRepo(root: string): Promise<RepoScan> {
  const files: string[] = [];

  async function walk(directory: string, relativeDirectory: string): Promise<void> {
    const entries = await readdir(directory, { withFileTypes: true });
    for (const entry of entries) {
      const relativePath = relativeDirectory ? `${relativeDirectory}/${entry.name}` : entry.name;
      if (isIgnored(relativePath)) {
        continue;
      }

      const absolutePath = join(directory, entry.name);
      if (entry.isDirectory()) {
        await walk(absolutePath, relativePath);
        continue;
      }

      if (entry.isFile()) {
        files.push(relativePath);
      }
    }
  }

  await walk(root, "");
  return { root, files: files.sort() };
}

async function detectStack(scan: RepoScan): Promise<StackDetection> {
  const packageJson = await readPackageJson(scan.root);
  const dependencies = readDependencies(packageJson);
  const languages = detectLanguages(scan);
  const packageManagers = detectPackageManagers(scan);
  const frameworks = await detectFrameworks(scan, dependencies);
  const commands = await detectCommands(scan, packageJson, languages);

  return {
    languages,
    frameworks,
    packageManagers,
    ciProviders: detectCiProviders(scan),
    testsPresent: detectTests(scan),
    commands
  };
}

function detectLanguages(scan: RepoScan): readonly string[] {
  const markers: readonly [string, boolean][] = [
    ["python", hasAny(scan, "pyproject.toml", "setup.py", "requirements.txt") || hasExtension(scan, ".py")],
    ["javascript", hasAny(scan, "package.json") || hasAnyExtension(scan, [".js", ".jsx", ".mjs", ".cjs"])],
    ["typescript", hasAny(scan, "tsconfig.json") || hasAnyExtension(scan, [".ts", ".tsx"])],
    ["rust", hasAny(scan, "Cargo.toml") || hasExtension(scan, ".rs")],
    ["go", hasAny(scan, "go.mod") || hasExtension(scan, ".go")],
    ["java", hasAny(scan, "pom.xml", "build.gradle", "build.gradle.kts") || hasExtension(scan, ".java")],
    ["dotnet", scan.files.some((file) => file.endsWith(".csproj") || file.endsWith(".fsproj") || file.endsWith(".sln"))],
    ["ruby", hasAny(scan, "Gemfile") || hasExtension(scan, ".rb")],
    ["php", hasAny(scan, "composer.json") || hasExtension(scan, ".php")]
  ];
  return markers.filter(([, present]) => present).map(([language]) => language);
}

function detectPackageManagers(scan: RepoScan): readonly string[] {
  const markers: readonly [string, boolean][] = [
    ["npm", hasAny(scan, "package-lock.json", "package.json")],
    ["pnpm", hasAny(scan, "pnpm-lock.yaml")],
    ["yarn", hasAny(scan, "yarn.lock")],
    ["pip", hasAny(scan, "requirements.txt")],
    ["poetry", hasAny(scan, "poetry.lock")],
    ["uv", hasAny(scan, "uv.lock")],
    ["cargo", hasAny(scan, "Cargo.toml")],
    ["go", hasAny(scan, "go.mod")],
    ["maven", hasAny(scan, "pom.xml")],
    ["gradle", hasAny(scan, "build.gradle", "build.gradle.kts")],
    ["dotnet", scan.files.some((file) => file.endsWith(".csproj") || file.endsWith(".fsproj") || file.endsWith(".sln"))],
    ["bundler", hasAny(scan, "Gemfile")],
    ["composer", hasAny(scan, "composer.json")]
  ];
  return markers.filter(([, present]) => present).map(([manager]) => manager);
}

async function detectFrameworks(scan: RepoScan, dependencies: ReadonlySet<string>): Promise<readonly string[]> {
  const frameworks = new Set<string>();
  const nodeFrameworks = new Map([
    ["react", "react"],
    ["next", "nextjs"],
    ["vite", "vite"],
    ["vue", "vue"],
    ["svelte", "svelte"],
    ["express", "express"],
    ["fastify", "fastify"],
    ["jest", "jest"],
    ["vitest", "vitest"],
    ["playwright", "playwright"]
  ]);

  for (const [dependency, framework] of nodeFrameworks) {
    if (dependencies.has(dependency)) {
      frameworks.add(framework);
    }
  }

  const pythonText = [
    await readOptional(join(scan.root, "requirements.txt")),
    await readOptional(join(scan.root, "pyproject.toml"))
  ].join("\n").toLowerCase();
  if (pythonText.length > 0) {
    for (const [marker, framework] of [
      ["django", "django"],
      ["fastapi", "fastapi"],
      ["flask", "flask"],
      ["pytest", "pytest"],
      ["ruff", "ruff"]
    ] as const) {
      if (pythonText.includes(marker)) {
        frameworks.add(framework);
      }
    }
  }

  return [...frameworks].sort();
}

function detectCiProviders(scan: RepoScan): readonly string[] {
  const providers: string[] = [];
  if (scan.files.some((file) => file.startsWith(".github/workflows/"))) {
    providers.push("github-actions");
  }
  if (hasAny(scan, ".gitlab-ci.yml")) {
    providers.push("gitlab-ci");
  }
  if (hasAny(scan, "azure-pipelines.yml")) {
    providers.push("azure-pipelines");
  }
  if (hasAny(scan, "bitbucket-pipelines.yml")) {
    providers.push("bitbucket-pipelines");
  }
  if (hasAny(scan, "Jenkinsfile")) {
    providers.push("jenkins");
  }
  return providers;
}

function detectTests(scan: RepoScan): boolean {
  return scan.files.some((file) => (
    file.startsWith("tests/")
    || file.startsWith("test/")
    || file.startsWith("__tests__/")
    || file.startsWith("spec/")
    || file.includes(".test.")
    || file.includes(".spec.")
    || basename(file).startsWith("test_")
    || basename(file).endsWith("_test.go")
  ));
}

async function detectCommands(
  scan: RepoScan,
  packageJson: Record<string, unknown>,
  languages: readonly string[]
): Promise<StackDetection["commands"]> {
  const lint: string[] = [];
  const test: string[] = [];
  const build: string[] = [];
  const scripts = readRecord(packageJson, "scripts");

  if (scripts) {
    const runner = nodeRunner(scan);
    for (const [script, bucket] of [
      ["test", test],
      ["lint", lint],
      ["build", build],
      ["typecheck", lint]
    ] as const) {
      if (typeof scripts[script] === "string") {
        bucket.push(`${runner} run ${script}`);
      }
    }
  }

  if (languages.includes("python")) {
    const pythonText = [
      await readOptional(join(scan.root, "requirements.txt")),
      await readOptional(join(scan.root, "pyproject.toml"))
    ].join("\n").toLowerCase();
    if (pythonText.includes("pytest") || hasAny(scan, "pytest.ini", "tox.ini")) {
      test.push("python -m pytest");
    } else {
      test.push("python -m unittest discover");
    }
    if (pythonText.includes("ruff")) {
      lint.push("python -m ruff check .");
    }
    if (hasAny(scan, "pyproject.toml")) {
      build.push("python -m build");
    }
  }
  if (languages.includes("rust")) {
    test.push("cargo test");
    lint.push("cargo clippy --all-targets --all-features");
    build.push("cargo build");
  }
  if (languages.includes("go")) {
    test.push("go test ./...");
    lint.push("go vet ./...");
    build.push("go build ./...");
  }
  if (languages.includes("java")) {
    if (hasAny(scan, "pom.xml")) {
      test.push("mvn test");
      build.push("mvn package");
    }
    if (hasAny(scan, "build.gradle", "build.gradle.kts")) {
      test.push("./gradlew test");
      build.push("./gradlew build");
    }
  }
  if (languages.includes("dotnet")) {
    test.push("dotnet test");
    build.push("dotnet build");
  }

  return {
    lint: unique(lint),
    test: unique(test),
    build: unique(build)
  };
}

function renderApoloYaml(repo: string, detectedStack: StackDetection): string {
  return [
    `# ${GENERATED_MARKER}`,
    "version: 1",
    "project:",
    `  name: ${yamlString(basename(repo))}`,
    "workspace:",
    "  plans: .apolo/plans",
    "  runs: .apolo/runs",
    "  memory: .apolo/memory",
    "commands:",
    "  lint:",
    yamlList(detectedStack.commands.lint, 4),
    "  test:",
    yamlList(detectedStack.commands.test, 4),
    "  build:",
    yamlList(detectedStack.commands.build, 4),
    "gates:",
    "  config: .apolo/gates.yaml",
    ""
  ].join("\n");
}

function renderGatesYaml(detectedStack: StackDetection): string {
  return [
    `# ${GENERATED_MARKER}`,
    "version: 1",
    "required:",
    "  - name: lint",
    "    commands:",
    yamlList(detectedStack.commands.lint, 6),
    "    allow_empty: true",
    "  - name: test",
    "    commands:",
    yamlList(detectedStack.commands.test, 6),
    "    allow_empty: true",
    "  - name: build",
    "    commands:",
    yamlList(detectedStack.commands.build, 6),
    "    allow_empty: true",
    "handoff:",
    "  require_session_handoff_update: true",
    "  require_quality_document_update: true",
    ""
  ].join("\n");
}

function renderProgressMarkdown(detectedStack: StackDetection): string {
  return [
    `<!-- ${GENERATED_MARKER} -->`,
    "# APOLO Progress",
    "",
    "## Current status",
    "",
    "- Harness initialized.",
    `- Detected languages: ${markdownList(detectedStack.languages)}`,
    `- Detected frameworks: ${markdownList(detectedStack.frameworks)}`,
    "- Validation commands are recorded in `.apolo/apolo.yaml`.",
    "",
    "## Next steps",
    "",
    "- Review detected commands before relying on them in automation.",
    "- Keep this progress log current when repository state changes.",
    ""
  ].join("\n");
}

function renderSessionHandoffMarkdown(repo: string): string {
  return [
    `<!-- ${GENERATED_MARKER} -->`,
    "# Session Handoff",
    "",
    "## Repository",
    "",
    basename(repo),
    "",
    "## Current work",
    "",
    "- No active handoff recorded yet.",
    "",
    "## Follow-up",
    "",
    "- Update this file with open risks, validation status, and next steps before handing off.",
    ""
  ].join("\n");
}

function renderQualityMarkdown(detectedStack: StackDetection): string {
  return [
    `<!-- ${GENERATED_MARKER} -->`,
    "# Quality Document",
    "",
    "## Detected validation",
    "",
    "### Lint",
    markdownCommands(detectedStack.commands.lint),
    "",
    "### Test",
    markdownCommands(detectedStack.commands.test),
    "",
    "### Build",
    markdownCommands(detectedStack.commands.build),
    "",
    "## Policy",
    "",
    "- Run available validation commands before handing off code changes.",
    "- Document unavailable commands or known gaps in this file.",
    ""
  ].join("\n");
}

async function readPackageJson(root: string): Promise<Record<string, unknown>> {
  try {
    const parsed: unknown = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
    return isRecord(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

function readDependencies(packageJson: Record<string, unknown>): ReadonlySet<string> {
  const names = new Set<string>();
  for (const key of ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"]) {
    const dependencies = readRecord(packageJson, key);
    if (!dependencies) {
      continue;
    }
    for (const dependency of Object.keys(dependencies)) {
      names.add(dependency);
    }
  }
  return names;
}

function readRecord(source: Record<string, unknown>, key: string): Record<string, unknown> | undefined {
  const value = source[key];
  return isRecord(value) ? value : undefined;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasAny(scan: RepoScan, ...relativePaths: readonly string[]): boolean {
  return relativePaths.some((path) => scan.files.includes(path));
}

function hasExtension(scan: RepoScan, extension: string): boolean {
  return scan.files.some((file) => file.endsWith(extension));
}

function hasAnyExtension(scan: RepoScan, extensions: readonly string[]): boolean {
  return extensions.some((extension) => hasExtension(scan, extension));
}

function isIgnored(relativePath: string): boolean {
  return relativePath.split("/").some((part) => IGNORED_DIRS.has(part));
}

function nodeRunner(scan: RepoScan): string {
  if (hasAny(scan, "pnpm-lock.yaml")) {
    return "pnpm";
  }
  if (hasAny(scan, "yarn.lock")) {
    return "yarn";
  }
  return "npm";
}

function unique(values: readonly string[]): readonly string[] {
  return [...new Set(values)];
}

function yamlList(values: readonly string[], indent: number): string {
  const prefix = " ".repeat(indent);
  if (values.length === 0) {
    return `${prefix}[]`;
  }
  return values.map((value) => `${prefix}- ${yamlString(value)}`).join("\n");
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function markdownList(values: readonly string[]): string {
  return values.length === 0 ? "unknown" : values.join(", ");
}

function markdownCommands(values: readonly string[]): string {
  if (values.length === 0) {
    return "- Not detected";
  }
  return values.map((value) => `- \`${value}\``).join("\n");
}

function formatArtifactPath(artifact: Artifact): string {
  return artifact.kind === "directory" ? `${artifact.relativePath}/` : artifact.relativePath;
}

function resolveArtifact(repo: string, relativePath: string): string {
  return join(repo, ...relativePath.split("/"));
}

async function statOrNull(path: string) {
  try {
    return await stat(path);
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return undefined;
    }
    throw error;
  }
}

async function readUtf8(path: string): Promise<string> {
  return readFile(path, "utf8");
}

async function readOptional(path: string): Promise<string> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return "";
    }
    throw error;
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
